USE [IN2]
GO

CREATE TABLE [dbo].[STUDENT]
(
	[StudentID] INT IDENTITY(1,1) NOT NULL ,
	[ImePrezime] NVARCHAR(255) NOT NULL,
	CONSTRAINT PK_STUDENT PRIMARY KEY (StudentID)
)

 GO

CREATE TABLE [dbo].[PREDMET]
(
	[PredmetID] INT IDENTITY(1,1) NOT NULL,
	[Naziv] NVARCHAR(255) NOT NULL,
	CONSTRAINT PK_PREDMET PRIMARY KEY (PredmetID)
)

GO 

CREATE TABLE [dbo].[POLOZENI_ISPITI]
(
	[ID] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[StudentID] INT NOT NULL,
	[PredmetID] INT NOT NULL,
	[Ocena] INT NOT NULL CHECK (Ocena > 5 AND Ocena <= 10),	
	CONSTRAINT FK_POLOZENI_ISPITI_STUDENT 
	FOREIGN KEY (StudentID) 
	REFERENCES STUDENT(StudentID) ON DELETE CASCADE,
	CONSTRAINT FK_POLOZENI_ISPITI_PREDMET
	FOREIGN KEY ([PredmetID]) 
	REFERENCES PREDMET(PredmetID) ON DELETE CASCADE
)

GO 
